<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Configuration.Binder" Version="3.1.2" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="3.1.2" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="3.1.2" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="3.1.2" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="3.1.2" />
    <PackageVersion Include="Roslynator.Analyzers" Version="2.3.0" />
    <PackageVersion Include="Roslynator.CodeFixes" Version="1.9.0" />
    <PackageVersion Include="Rundeck.Api" Version="34.0.60" />
    <PackageVersion Include="Nerdbank.GitVersioning" Version="3.9.50" />
  </ItemGroup>
</Project>