<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<IsPackable>false</IsPackable>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="xunit.v3" />
		<PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\content\Rundeck.Cli.csproj" />
	</ItemGroup>
</Project>
